database:
  host: "localhost"
  user: "postgres"
  password: "mesika"
  name: "grpc"

oauth:
  client_id: ""
  client_secret: ""
  redirect_url: "http://localhost:8080/api/auth/callback"

session:
  secret: ""
